#!/bin/bash

BASE_DIR=$(dirname "$(readlink -f "$0")")
NAME="paralarva-prometheus"
MINIKUBE_IP=$(minikube ip)
# shellcheck disable=SC2181
if [[ ${?} -ne 0 ]]; then
    echo "Could not get minikube ip address; exiting"
    exit 2
fi

cat << EOF > "${BASE_DIR}"/etc/prometheus.yml
# !!!  this file was generated by $(basename "$0") !!!
# !!/!\\!! do not modify manually as changes may be overridden !!/!\\!!

EOF
sed "s/MINIKUBE_IP/${MINIKUBE_IP}/" "${BASE_DIR}"/prometheus.tpl >> "${BASE_DIR}"/etc/prometheus.yml

echo "removing container ${NAME} if it already exits"
docker rm --force "$(docker ps -a -f "name="${NAME} --format '{{.ID}}')" > /dev/null 2>&1
ID=$(docker run -d --name ${NAME} --network=host -v "${BASE_DIR}"/etc:/etc/prom prom/prometheus --web.enable-lifecycle --config.file=/etc/prom/prometheus.yml)
echo "container ${NAME} created with ID ${ID}"