apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-app
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.config.proxy.listen.port }}
      targetPort: {{ .Values.app.config.proxy.listen.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: {{ include "chart.fullname" . }}-app
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
